config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'
  resources :posts
  resources :pictures, only: [:create, :destroy]
  resources :tags, only: [:show]
  resources :categories

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts

  validates :name, presence: true

  has_ancestry

end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  serialize :image, JSON
end

app/models/post.rb
class Post < ApplicationRecord
#class Post < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  belongs_to :category

  validates :title, :summary, :body, presence: true

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :taggings
  has_many :posts, through: :taggings

  def self.counts
    self.select('name, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  end

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  add_flash_types :success, :danger, :info, :warning
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
    @posts = Post.where(category_id: [@category.subtree_ids]).paginate(page: params[:page], per_page: 2)
  end

  def new
    @category = Category.new
    @categories = Category.all.order(:name)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, succes: 'Категория успешно создана'
    else
      @categories = Category.all.order(:name)
      flash[:danger] = 'Категория не создана'
      render :new
    end
  end

  def edit
    @categories = Category.where("id != #{@category.id}").order(:name)
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to categories_path, succes: 'Категория успешно обновлена'
    else
      @categories = Category.where("id != #{@category.id}").order(:name)
      flash[:danger] = 'Категория не обновлена'
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, succes: 'Категория успешно удалена'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :parent_id)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def create
    @picture = Picture.new(image_params)
    @picture.save
    respond_to do |format|
      format.json {render :json => {url: @picture.image.url(:large), picture_id: @picture.id}}
    end
  end

  def destroy
    picture = Picture.find(params[:id])
    picture.destroy
    respond_to do |format|
      format.json { render json: { status: :ok}}
    end
  end

  private

  def image_params
    params.require(:picture).permit(:image)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 2)
  end

  def show
    #@post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, success: 'Article successfully created'
    else
      flash.now[:danger] = 'Статья не создана'
      render :new
    end
  end

    def edit
      #@post = Post.find(params[:id])
    end


  def update
    #@post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to @post, success: 'Статья успешно обновлена'
    else
      flash.now[:danger] = 'Статья не обновлена'
      render :edit
    end
  end

  def destroy
    #@post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, success: 'Article successfully deleted'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :summary, :body, :all_tags, :category_id, :image)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by(name: params[:id])
    @posts = @tag.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
    <div class="alert alert-danger">
      <h5><%= t('common.errors') %></h5>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for @category do |f| %>

    <div class="form-group">
      <%= f.label :name  %>
      <%= f.text_field :name, class: 'form-control'  %>
    </div>

    <div class="form-group">
      <%= f.label :parent_id %>
      <%= f.collection_select :parent_id, @categories, :id, :name, { include_blank:true },
                              class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= f.submit t('.submit', action: @category.new_record? ? 'Создать' : 'Изменить'), class: 'btn btn-primary' %>
      <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1><%= t('.title') %></h1>

<div class="buttons_panel">
  <%= link_to 'Новая категория', new_category_path, class: 'btn btn-outline-primary btn-sm' %>
</div>

<section id = 'categories'>
  <table class="table">
    <thead>
    <tr>
      <th>#</th>
      <th>Название</th>
      <th>Категория родитель</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @categories.each_with_index do |category, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= category.name %></td>
      <td><%= category.parent.name if category.parent.present? %></td>
      <td>
        <%= link_to 'Изменить', edit_category_path(category), class: 'btn btn-outline-primary btn-sm' %>
        <%= link_to 'Удалить', category_path(category),  method: :delete, data: {confirm: 'Вы уверены?'}, class: 'btn btn-outline-danger btn-sm' %>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>
</section>

app/views/categories/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<section id = 'posts'>
  <%= render @posts %>
</section>

<div class="digg_pagination">
  <%= will_paginate @posts %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <nav class="navbar  navbar-light bg-light">
    <ul class="nav justify-content-end">
      <li class="nav-item active">
        <a class="nav-link" href="<%= posts_path %>">Articles</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Contacts</a>
      </li>
    </ul>
    <%= link_to 'New article', new_post_path, class: 'btn btn-outline-primary pull-xs-right' %>
  </nav>
  </div>

 <div class="container main">
   <div class="row">
     <div class="col-md-12">
       <% flash.each do |name, message| %>
       <div class="alert alert-<%= name %>">
         <%= message %>
       </div>
       <% end %>
     </div>
   </div>

   <div class="row">
    <div class="col-md-9">
      <%= yield %>
    </div>

    <div class="col-md-3">
      <%= render 'shared/submenu' %>
      <div class="tag_cloud">
      <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class| %>
        <%= link_to tag.name, tag_path(tag.name), class: css_class %>
      <% end %>
      </div>
    </div>
   </div>
 </div>
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    var disqus_config = function () {
        this.page.url = 'http://localhost.com<%= request.original_fullpath %>';  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = <%= @post.id %>; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://blogdevsimple-8.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post, html: { multipart: true} do |f| %>

    <div class="form-group">
      <%= f.label :title  %>
      <%= f.text_field :title, class: 'form-control'  %>
    </div>

    <div class="form-group">
      <%= f.label :summary  %>
      <%= f.text_area :summary, class: 'form-control'  %>
    </div>

    <div class="form-group">
      <%= f.label :body  %>
      <%= f.trix_editor :body, class: 'editor'  %>
    </div>

    <div class="form-group">
      <%= f.label :category_id %>
      <%= f.collection_select :category_id, Category.order(:name), :id, :name, { includ_blanck: true}, class: 'form-control'  %>
    </div>


    <div class="form-group">
      <%= f.label :all_tags  %>
      <%= f.text_field :all_tags, class: 'form-control'  %>
    </div>

    <div class="form-group">
      <%= f.file_field :image  %>
    </div>

    <div class="form-group">
      <%= f.submit t('.submit', action: @post.new_record? ? 'Создать' : 'Изменить'), class: 'btn btn-primary' %>
      <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
    </div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <small>
      <time><%= post.created_at.to_date.strftime('%d %B, %Y') %></time>
      <% if post.category.present? %>
      |
      <%= link_to post.category.name, post.category %>
          <% end %>
      |
      <%= link_to 'Edit', edit_post_path(post) %>
      |
      <%= link_to 'Delete', post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %>
    </small>
  </section>

  <section class="post-summary clearfix">
    <%= image_tag post.image.url(:thumb), class: 'img-thumbnail thumb' if post.image? %>
    <%= post.summary %>
  </section>

  <section class="footer-summary">
    <%= raw post.tags.map(&:name).map{|t| link_to t, tag_path(t), class: 'tag tag-info' }.join(' ') %>
  </section>
</article>

app/views/posts/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1><%= t('.title') %></h1>

<%= render @posts %>
<div class="digg_pagination">
  <%= will_paginate @posts %>
</div>

app/views/posts/new.html.erb
<h1><%=t('posts.new.title')%></h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<article class="post">
  <section class="post-head">
    <h1><%= @post.title %></h1>
    <small>
      <time><%= @post.created_at.to_date.strftime('%d %B, %Y') %></time>
      <% if @post.category.present? %>
          |
          <%= link_to @post.category.name, @post.category %>
      <% end %>
      |
      <%= link_to 'Edit', edit_post_path(@post) %>
      |
      <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'} %>
    </small>
  </section>

  <section class="post-body">
    <%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %>
    <%= @post.body.html_safe %>
  </section>
</article>

<%= render 'disqus' %>

app/views/shared/_submenu.html.erb
<div class="submenu">
  <h2>Категории</h2>
  <ul class="nav nav-pills nav-stacked">
    <% Category.roots.each do|category| %>
      <li class="nav-item">
        <%= link_to category.name, category, class: "nav-link #{'active' if current_page?(category_path(category)) || @post.present? &&
            @post.category == category}" %>
        <%= render 'shared/submenu_categories', categories: category.root.descendants.arrange %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_submenu_categories.html.erb
<ul class="nav nav-pills nav-stacked nested_nav">
  <% categories.each do |category, children| %>
    <li>
      <%= link_to category.name, category, class: "nav-link #{'active' if current_page?(category_path(category))|| @post.present? &&
          @post.category == category}" %>
      <%= render 'shared/submenu_categories', categories: children if children.present? %>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<% if @tag.posts.empty? %>
    <h2>No articles</h2>
<% else %>
    <%= render @tag.posts %>
<% end %>